import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Nuvance Technologies | Title",
//   description: "Generated by Developers in NuvanceTech",
// };


export const metadata = {
    title: "Nuvance Technologies | Your Tech Partner",
    description: "Nuvance Technologies offers expert IT solutions including web development, app development, AI/ML, cloud services, and more.",
    keywords: [
        "Nuvance Technologies", "Nuvance Tech", "Nuvance Technology", "Nuvance", "Nuvance IT Solutions",
        "Nuvance Technologies Website", "Nuvance Technologies India", "Web development company", "Website Development",
        "AI/ML Solution", "Cloud Services", "SEO Optimization", "Custom software development", "Mobile app development",
        "Frontend development", "Backend development", "Full-stack development", "Tech startup India", "Top software company",
        "Enterprise IT solutions", "Tech company in India", "Website design and development", "Business software solutions",
        "Software consulting", "Modern web development", "Affordable IT services"
    ],
    openGraph: {
        title: "Nuvance Technologies",
        description: "Expert IT solutions: Web and App Development, Cloud Services, AI/ML, SEO Optimization by Nuvance Technologies.",
        url: "https://nuvancetechnologies.com",
        siteName: "Nuvance Technologies",
        images: [
            {
                url: "/og-image.png",
                width: 1200,
                height: 630,
            },
        ],
        type: "website",
    },
    icons: {
        icon: "/favicon.ico",
    },
};



export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
